"""Characterization harness — pins observable behaviour across a refactor.

The unit suite monkeypatches module globals (`fb.CFG`, `fb.git_info`, `fb._cache`, …) at 67
sites. That coupling is exactly what a module split breaks, and it breaks it *silently*: once
`collect_state` lives in `observer.py` and imports `git_info` by name, patching
`orchestra.git_info` stops having any effect and the test keeps passing while testing nothing.

So the unit suite cannot be its own safety net for this change. This harness is the net instead:

  * it patches NOTHING — it only calls public functions with explicit arguments,
  * it locates the code through `load_orchestra()`, which resolves either the single-file
    layout or the package layout, so the SAME harness runs on both sides of the split,
  * it records a golden JSON and compares against it, so "behaviour is identical" is a
    byte-comparison rather than an opinion.

Usage:
    python3 tests/characterize.py --record     # before the refactor
    python3 tests/characterize.py              # after — must be byte-identical
    python3 -m unittest tests.test_characterization   # same check, as a test

Because it asserts on the public surface only, it also proves the package facade is complete:
if the split forgets to re-export something, loading fails here first.
"""

import argparse
import hashlib
import importlib.util
import itertools
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
GOLDEN = ROOT / "tests" / "golden" / "characterization.json"


def load_orchestra():
    """Import the app under either layout.

    Single file today (`orchestra.py`); a package after the split
    (`orchestra/__init__.py`). Everything this harness touches must be reachable from the
    top-level name in both, which is the facade contract.
    """
    pkg_init = ROOT / "orchestra" / "__init__.py"
    single = ROOT / "orchestra.py"
    if pkg_init.exists():
        sys.path.insert(0, str(ROOT))
        import orchestra as mod
        return mod, "package"
    if single.exists():
        spec = importlib.util.spec_from_file_location("orchestra", single)
        mod = importlib.util.module_from_spec(spec)
        sys.modules["orchestra"] = mod
        spec.loader.exec_module(mod)
        return mod, "single-file"
    raise SystemExit("no orchestra.py and no orchestra/ package found")


# ------------------------------------------------------------------ input space

def _classify_inputs():
    ages = [0, 1, 5, 19, 20, 59, 60, 89, 90, 91, 200, 3600]
    pends = [[], ["AskUserQuestion"], ["Bash"], ["Read", "Bash"], ["AskUserQuestion", "Bash"]]
    for age, alive, pend, deleg, skip, shells in itertools.product(
            ages, [True, False], pends, [0, 1, 3], [True, False], [0, 1]):
        yield dict(age_s=age, alive=alive, pending_tools=pend, delegated=deleg,
                   skip_perms=skip, working_s=90, shells=shells)


def _closeout_inputs():
    statuses = [None, "working", "needs_input", "blocked", "waiting", "ended", "unknown"]
    for st, anyw, sent, now in itertools.product(
            statuses, [True, False], [0, 940, 1000], [1000]):
        yield dict(paired_status=st, any_working=anyw, sent=sent, now=now)


TEXTS = [
    "", "   ", "hello world",
    "\x1b[31mred\x1b[0m text",
    "<command-name>/effort</command-name>",
    "Caveat: The messages below were generated by the user while running local commands.",
    "This session is being continued from a previous conversation that ran out of context.",
    "The user opened the file /tmp/x.py in the IDE.",
    "<system-reminder>noise</system-reminder>",
    "line one\nline two\n\n\nline three",
    "  leading and trailing  ",
    "a" * 400,
    "🚀 unicode ⌁ glyphs ▲ ⛔",
]

PATHS = [
    "/Users/a/code/myapp", "/Users/a/code/myapp-audit", "/Users/a/code/other",
    "/Users/a/code", "/", "/Users/a/code/myapp/sub", "relative/path",
]


def _safe(mod, name, *args, **kw):
    """Call a public function, recording either its value or its failure signature.

    A refactor must preserve how a function fails, not merely how it succeeds.
    """
    fn = getattr(mod, name, None)
    if fn is None:
        return {"__missing__": name}
    try:
        return fn(*args, **kw)
    except Exception as exc:                      # noqa: BLE001 — recording is the point
        return {"__raised__": type(exc).__name__, "__msg__": str(exc)[:200]}


# ------------------------------------------------------------------ the snapshot

def build(mod):
    snap = {}

    snap["classify_session"] = [
        {"in": kw, "out": _safe(mod, "classify_session", **kw)} for kw in _classify_inputs()
    ]
    snap["closeout_step"] = [
        {"in": kw, "out": _safe(mod, "closeout_step", **kw)} for kw in _closeout_inputs()
    ]

    snap["munge"] = [{"in": p, "out": _safe(mod, "munge", p)} for p in PATHS]

    prefixes = {p: _safe(mod, "munge", p) for p in PATHS if not p.startswith("relative")}
    snap["match_worktree"] = [
        {"in": name, "out": _safe(mod, "match_worktree", name, prefixes)}
        for name in list(prefixes.values()) + ["-Users-a-code-myapp-extra", "unrelated", ""]
    ]

    snap["_clean"] = [{"in": t, "out": _safe(mod, "_clean", t)} for t in TEXTS]
    snap["_real_prompt"] = [{"in": t, "out": _safe(mod, "_real_prompt", t)} for t in TEXTS]
    snap["_osa_escape"] = [
        {"in": t, "out": _safe(mod, "_osa_escape", t)}
        for t in ['plain', 'has "quotes"', "back\\slash", "new\nline", "", "⌁ unicode"]
    ]

    snap["account_label"] = [
        {"in": h, "out": _safe(mod, "account_label", pathlib.Path(h))}
        for h in ["/Users/a/.claude", "/Users/a/.claude-work", "/Users/a/.claude-spare",
                  "/Users/a/.claude-", "/Users/a/other"]
    ]

    # per-model headroom + reserve: the policy the account picker duplicated and drifted from
    accounts = [
        {"label": "main", "plan": "max", "headroom_percent": 62,
         "limits": [{"name": "session", "used_percent": 21},
                    {"name": "weekly", "used_percent": 38}]},
        {"label": "work", "plan": "max", "headroom_percent": 0,
         "limits": [{"name": "session", "used_percent": 100},
                    {"name": "weekly", "used_percent": 91}]},
        {"label": "spare", "plan": "pro", "headroom_percent": 88,
         "limits": [{"name": "session", "used_percent": 4},
                    {"name": "weekly", "used_percent": 12}]},
    ]
    snap["_model_remaining"] = [
        {"in": {"account": a["label"], "model": m},
         "out": _safe(mod, "_model_remaining", a, m)}
        for a in accounts for m in [None, "opus", "sonnet", "haiku", "fable"]
    ]
    snap["account_reserve"] = [
        {"in": lbl, "out": _safe(mod, "account_reserve", lbl)}
        for lbl in ["main", "work", "spare", "unknown"]
    ]
    snap["_limit_active_until"] = [
        {"in": lim, "out": _safe(mod, "_limit_active_until", lim)}
        for lim in [{}, {"resets_at": 0}, {"resets_at": 1784650000},
                    {"name": "weekly", "resets_at": 1784650000, "used_percent": 100}]
    ]

    snap["card_availability"] = [
        {"in": {"sessions": s, "procs": p},
         "out": _safe(mod, "card_availability", s, p)}
        for s in ([], [{"status": "working"}], [{"status": "ended"}],
                  [{"status": "waiting"}, {"status": "ended"}],
                  [{"status": "needs_input"}], [{"status": "limit"}])
        for p in ([], [{"pid": 1}], [{"pid": 1}, {"pid": 2}])
    ]

    snap["session_topic"] = [
        {"in": t, "out": _safe(mod, "session_topic", t)} for t in TEXTS
    ]

    return snap


def digest(snap):
    """Per-section digests, so a diff names the function that moved rather than 'something'."""
    out = {}
    for k, v in sorted(snap.items()):
        blob = json.dumps(v, sort_keys=True, default=str).encode()
        out[k] = {"sha256": hashlib.sha256(blob).hexdigest()[:16], "cases": len(v)}
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--record", action="store_true", help="write the golden file")
    ap.add_argument("--show", action="store_true", help="print per-section digests")
    args = ap.parse_args()

    mod, layout = load_orchestra()
    snap = build(mod)
    dig = digest(snap)

    if args.show:
        for k, v in dig.items():
            print(f"  {v['sha256']}  {v['cases']:5d} cases  {k}")

    total = sum(v["cases"] for v in dig.values())

    if args.record:
        GOLDEN.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN.write_text(json.dumps({"digests": dig, "snapshot": snap},
                                     sort_keys=True, indent=1, default=str))
        print(f"recorded {total} cases across {len(dig)} functions "
              f"({layout} layout) -> {GOLDEN.relative_to(ROOT)}")
        return 0

    if not GOLDEN.exists():
        print("no golden file; run with --record first", file=sys.stderr)
        return 2

    want = json.loads(GOLDEN.read_text())
    drift = [k for k in sorted(set(want["digests"]) | set(dig))
             if want["digests"].get(k, {}).get("sha256") != dig.get(k, {}).get("sha256")]
    if not drift:
        print(f"characterization OK — {total} cases identical ({layout} layout)")
        return 0

    print(f"BEHAVIOUR CHANGED in {len(drift)} function(s) ({layout} layout):", file=sys.stderr)
    for k in drift:
        print(f"  {k}", file=sys.stderr)
        old = {json.dumps(c, sort_keys=True, default=str)
               for c in want["snapshot"].get(k, [])}
        new = {json.dumps(c, sort_keys=True, default=str) for c in snap.get(k, [])}
        for line in sorted(new - old)[:3]:
            print(f"    now: {line[:200]}", file=sys.stderr)
        for line in sorted(old - new)[:3]:
            print(f"    was: {line[:200]}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
