#!/usr/bin/env python3
"""orchestra test suite — pure stdlib unittest, zero dependencies.

    python3 -m unittest discover -s tests        # from repo root
    python3 tests/test_orchestra.py             # or run directly

The server only starts from `python3 -m orchestra` (orchestra/__main__.py), so
importing the package here does NOT start it. Data-driven functions read module
globals (CFG, _limits, DEMO); tests set those and restore them.
"""

import json
import shlex
import sys
import tempfile
import threading
import unittest
import urllib.request
from http.server import ThreadingHTTPServer
from pathlib import Path

# ---- import the orchestra package from the repo root ----------------------
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
import orchestra as fb  # noqa: E402


def acc(config_dir, ok=True, headroom=None, limits=None):
    """Build a cclimits-shaped account dict."""
    return {"slug": Path(config_dir).name, "config_dir": config_dir, "ok": ok,
            "plan": "max", "headroom_percent": headroom, "limits": limits or []}


def lim(label, pct, model_scoped=False, exhausted=False, resets_in=None):
    return {"label": label, "group": "weekly" if label != "Session" else "session",
            "percent": pct, "remaining_percent": 100 - pct,
            "model_scoped": model_scoped, "exhausted_now": exhausted,
            "resets_in_seconds": resets_in}


class ConfigGuard(unittest.TestCase):
    """Snapshot & restore the module globals tests mutate."""
    def setUp(self):
        self._cfg = dict(fb.CFG)
        self._limits = dict(fb._limits)
        self._demo = fb.config.DEMO
        self._cpath = fb.config.CONFIG_PATH

    def tearDown(self):
        fb.CFG.clear(); fb.CFG.update(self._cfg)
        fb._limits.clear(); fb._limits.update(self._limits)
        fb.config.DEMO = self._demo
        fb.config.CONFIG_PATH = self._cpath


# ---------------------------------------------------------------- text utils

class TestText(ConfigGuard):
    def test_clean_strips_ansi(self):
        self.assertEqual(fb._clean("\x1b[1mHi\x1b[22m there"), "Hi there")

    def test_clean_collapses_whitespace_and_tags(self):
        self.assertEqual(fb._clean("a\n\n  b   <x>c</x>"), "a b c")

    def test_clean_truncates_with_ellipsis(self):
        out = fb._clean("a" * 300, 240)
        self.assertEqual(len(out), 240)
        self.assertTrue(out.endswith("…"))

    def test_real_prompt_rejects_slash_command(self):
        self.assertIsNone(fb._real_prompt("/model opus"))

    def test_real_prompt_rejects_caveat_and_machine_text(self):
        self.assertIsNone(fb._real_prompt("Caveat: generated by a local command"))
        self.assertIsNone(fb._real_prompt("<command-message>effort</command-message>"))
        self.assertIsNone(fb._real_prompt("<system-reminder>hi</system-reminder>"))
        self.assertIsNone(fb._real_prompt("here is toolu_01ABCdef noise"))
        self.assertIsNone(fb._real_prompt("<local-command-stdout>x</local-command-stdout>"))

    def test_real_prompt_accepts_real_text(self):
        self.assertEqual(fb._real_prompt("Build a dark-mode toggle"),
                         "Build a dark-mode toggle")

    def test_osa_escape(self):
        self.assertEqual(fb._osa_escape('a"b\\c'), 'a\\"b\\\\c')


# ------------------------------------------------------------ account / paths

class TestAccounts(ConfigGuard):
    def test_account_label(self):
        self.assertEqual(fb.account_label(Path.home() / ".claude"), "main")
        self.assertEqual(fb.account_label(Path.home() / ".claude-account8"), "account8")
        self.assertEqual(fb.account_label(Path.home() / ".claude-work"), "work")

    def test_munge(self):
        self.assertEqual(fb.munge("/Users/a/Downloads/ConfidAI"),
                         "-Users-a-Downloads-ConfidAI")

    def test_account_reserve_lookup_and_default(self):
        fb.CFG["reserve_percent"] = {"main": 20, "*": 5}
        self.assertEqual(fb.account_reserve("main"), 20)
        self.assertEqual(fb.account_reserve("account2"), 5)   # falls back to "*"
        fb.CFG["reserve_percent"] = {}
        self.assertEqual(fb.account_reserve("main"), 0)


# ---------------------------------------------------------- worktree matching

class TestMatchWorktree(unittest.TestCase):
    def test_longest_prefix_wins(self):
        prefixes = {"/d/ConfidAI": fb.munge("/d/ConfidAI"),
                    "/d/ConfidAI-security-audit": fb.munge("/d/ConfidAI-security-audit")}
        # a project under the audit worktree must not be swallowed by ConfidAI
        proj = fb.munge("/d/ConfidAI-security-audit") + "-backend"
        self.assertEqual(fb.match_worktree(proj, prefixes), "/d/ConfidAI-security-audit")

    def test_exact_and_subdir_match(self):
        prefixes = {"/d/app": fb.munge("/d/app")}
        self.assertEqual(fb.match_worktree(fb.munge("/d/app"), prefixes), "/d/app")
        self.assertEqual(fb.match_worktree(fb.munge("/d/app") + "-sub", prefixes), "/d/app")

    def test_no_match(self):
        prefixes = {"/d/app": fb.munge("/d/app")}
        self.assertIsNone(fb.match_worktree(fb.munge("/d/other"), prefixes))


# --------------------------------------------------------- session status

class TestClassifySession(unittest.TestCase):
    W = 90  # working_s

    def test_recent_is_working_regardless_of_liveness(self):
        self.assertEqual(fb.classify_session(5, False, [], 0, False, self.W)[0], "working")

    def test_needs_input_on_pending_question(self):
        st, _ = fb.classify_session(200, True, ["AskUserQuestion"], 0, False, self.W)
        self.assertEqual(st, "needs_input")

    def test_pending_workflow_keeps_working(self):
        st, _ = fb.classify_session(3600, True, [], 1, False, self.W)
        self.assertEqual(st, "working")

    def test_skip_perms_tool_run_is_working_not_blocked(self):
        st, tool = fb.classify_session(200, True, ["Bash"], 0, True, self.W)
        self.assertEqual(st, "working")
        self.assertTrue(tool)

    def test_pending_tool_without_skip_perms_is_blocked(self):
        st, _ = fb.classify_session(200, True, ["Bash"], 0, False, self.W)
        self.assertEqual(st, "blocked")

    def test_idle_alive_is_waiting(self):
        self.assertEqual(fb.classify_session(200, True, [], 0, False, self.W)[0], "waiting")

    def test_not_alive_is_ended(self):
        self.assertEqual(fb.classify_session(200, False, [], 0, False, self.W)[0], "ended")

    def test_live_shell_is_working_even_with_idle_transcript(self):
        # the ConfidAI-ci-cleanup case: turn ended ("1 shell still running"),
        # transcript untouched for minutes, but a backgrounded verify build is
        # a live child of the claude process — the agent resumes on its own
        st, tool = fb.classify_session(870, True, [], 0, False, self.W, shells=1)
        self.assertEqual(st, "working")
        self.assertTrue(tool)

    def test_live_shell_beats_blocked(self):
        st, _ = fb.classify_session(200, True, ["Bash"], 0, False, self.W, shells=1)
        self.assertEqual(st, "working")

    def test_pending_question_outranks_live_shell(self):
        st, _ = fb.classify_session(200, True, ["AskUserQuestion"], 0, False, self.W, shells=1)
        self.assertEqual(st, "needs_input")


class TestCloseoutStep(unittest.TestCase):
    """Step two (✕ close) when the landing won't verify — the pure decision
    that breaks the idle-agent / refusing-forever deadlock. One assertion per
    row of the table, plus the 60s boundary exactly at and just under."""

    def test_any_working_refuses_even_if_paired_is_idle(self):
        # a working session may be mid-closeout — never type over it, no matter
        # how the paired session looks or how long ago the brief went out
        self.assertEqual(
            fb.closeout_step("waiting", True, sent=0, now=10_000), "refuse")

    def test_stuck_agent_is_sent_to_chat_not_nudged(self):
        # a nudge typed here would collide with the open question/approval dialog
        self.assertEqual(
            fb.closeout_step("needs_input", False, sent=0, now=10_000), "chat")
        self.assertEqual(
            fb.closeout_step("blocked", False, sent=0, now=10_000), "chat")

    def test_idle_waiting_past_the_guard_gets_nudged(self):
        self.assertEqual(
            fb.closeout_step("waiting", False, sent=0, now=61), "nudge")

    def test_nudge_fires_exactly_at_the_60s_boundary(self):
        self.assertEqual(
            fb.closeout_step("waiting", False, sent=0, now=60), "nudge")

    def test_just_under_60s_refuses_the_double_type(self):
        self.assertEqual(
            fb.closeout_step("waiting", False, sent=0, now=59.9), "refuse")

    def test_scan_miss_never_types_blind(self):
        # no session paired with the live pid -> paired_status is None
        self.assertEqual(
            fb.closeout_step(None, False, sent=0, now=10_000), "refuse")


class TestShellChildren(unittest.TestCase):
    """Attribute Bash-tool wrapper shells to their claude ancestor."""

    # real wrapper shapes observed on macOS (2.1.215), one per variant
    SNAP = ("/bin/zsh -c source /Users/x/.claude-account6/shell-snapshots/"
            "snapshot-zsh-1784.sh 2>/dev/null || true && eval 'sleep 99' "
            "< /dev/null && pwd -P >| /tmp/claude-4632-cwd")
    BARE = ("/bin/zsh -c -l setopt NO_EXTENDED_GLOB NO_BARE_GLOB_QUAL "
            "2>/dev/null || true && eval 'scripts/verify.sh' < /dev/null "
            "&& pwd -P >| /tmp/claude-8a66-cwd")

    def test_counts_wrappers_under_their_claude(self):
        table = {
            100: (1, "??", "claude --dangerously-skip-permissions"),
            101: (100, "??", self.SNAP),
            102: (100, "??", self.BARE),
            200: (1, "??", "claude"),
        }
        self.assertEqual(fb.shell_children(table, {100, 200}), {100: 2})

    def test_plain_shells_and_orphans_do_not_count(self):
        table = {
            100: (1, "??", "claude"),
            101: (100, "??", "/bin/zsh -c ls"),          # not a Bash-tool wrapper
            102: (1, "??", self.SNAP),                   # no claude ancestor
            103: (100, "??", "-zsh"),                    # interactive login shell
        }
        self.assertEqual(fb.shell_children(table, {100}), {})

    def test_walks_intermediate_wrappers(self):
        table = {
            100: (1, "??", "claude"),
            150: (100, "??", "some-wrapper"),
            151: (150, "??", self.BARE),
        }
        self.assertEqual(fb.shell_children(table, {100}), {100: 1})


# -------------------------------------------------------- kickoff delivery

class TestKickoffSent(unittest.TestCase):
    """A dispatch must prove its brief left the composer — the observed
    failure was paste chips sitting unsent while the board said launched."""

    STUCK = ("│ /effort xhigh\n"
             "│   Set effort level to xhigh (saved as your default)\n"
             "────────────\n"
             "❯ [Pasted text #1][Pasted text #2] the long term, we will need\n"
             "  evals here. Just analyze it for now.\n"
             "────────────\n"
             "  ⏵⏵ bypass permissions on (shift+tab to cycle)\n")

    MID_TURN = ("⏺ I'll start by setting up a proper branch and orienting.\n"
                "✽ Imagining… (30s · ↓ 1.4k tokens)\n"
                "────────────\n"
                "❯ \n"
                "────────────\n"
                "  ⏵⏵ bypass permissions on · esc to interrupt\n")

    IDLE_EMPTY = ("⏺ Done.\n"
                  "────────────\n"
                  "❯ \n"
                  "────────────\n"
                  "  ⏵⏵ bypass permissions on (shift+tab to cycle)\n")

    def test_brief_still_in_composer_is_not_sent(self):
        self.assertFalse(fb.kickoff_sent(self.STUCK))

    def test_running_turn_proves_sent(self):
        self.assertTrue(fb.kickoff_sent(self.MID_TURN))

    def test_empty_composer_proves_sent(self):
        self.assertTrue(fb.kickoff_sent(self.IDLE_EMPTY))

    def test_blank_pane_is_not_sent(self):
        self.assertFalse(fb.kickoff_sent(""))


# ------------------------------------------------------- card availability

class TestCardAvailability(unittest.TestCase):
    """Limit-stuck cards read 'waiting', never 'needs you' — you can't act
    on an exhausted account, only wait for its reset."""

    def test_limit_only_is_waiting_not_attention(self):
        self.assertEqual(fb.card_availability(["limit"], True), "waiting")

    def test_idle_agent_next_to_limit_still_needs_direction(self):
        self.assertEqual(fb.card_availability(["limit", "waiting"], True), "attention")

    def test_limit_plus_working_is_busy(self):
        self.assertEqual(fb.card_availability(["limit", "working"], True), "busy")

    def test_question_or_blocked_beats_limit(self):
        self.assertEqual(fb.card_availability(["needs_input", "limit"], True), "attention")
        self.assertEqual(fb.card_availability(["blocked", "limit"], True), "attention")

    def test_no_live_proc_is_free(self):
        self.assertEqual(fb.card_availability(["ended"], False), "free")


# ------------------------------------------------ session <-> terminal pairing

class TestPairSessionsWithProcs(unittest.TestCase):
    """Which terminal belongs to which chat, for a worktree running several."""

    def _s(self, sid, account, age):
        return {"sid": sid, "account": account, "age_s": age}

    def _p(self, pid, account):
        return {"pid": pid, "account": account}

    def test_pairs_by_account(self):
        sessions = [self._s("a", "work", 10), self._s("b", "personal", 20)]
        procs = [self._p(1, "personal"), self._p(2, "work")]
        owner = fb.pair_sessions_with_procs(sessions, procs)
        self.assertEqual(owner["a"]["pid"], 2)
        self.assertEqual(owner["b"]["pid"], 1)

    def test_account_match_beats_freshness(self):
        # the fresher session has no process on its account; it must not take
        # the one that demonstrably belongs to the older session
        sessions = [self._s("fresh", "spare", 5), self._s("old", "work", 900)]
        procs = [self._p(7, "work")]
        owner = fb.pair_sessions_with_procs(sessions, procs)
        self.assertNotIn("fresh", owner)
        self.assertEqual(owner["old"]["pid"], 7)

    def test_falls_back_to_freshness_when_account_unknown(self):
        # environment unreadable -> accounts are None -> old slot behaviour
        sessions = [self._s("a", "work", 10), self._s("b", "work", 20)]
        procs = [self._p(1, None)]
        owner = fb.pair_sessions_with_procs(sessions, procs)
        self.assertEqual(owner["a"]["pid"], 1)
        self.assertNotIn("b", owner)

    def test_never_assigns_one_process_twice(self):
        sessions = [self._s("a", "work", 10), self._s("b", "work", 20)]
        procs = [self._p(1, "work")]
        owner = fb.pair_sessions_with_procs(sessions, procs)
        self.assertEqual(len(owner), 1)
        self.assertEqual({o["pid"] for o in owner.values()}, {1})

    def test_more_procs_than_sessions_leaves_leftovers(self):
        sessions = [self._s("a", "work", 10)]
        procs = [self._p(1, "work"), self._p(2, "spare")]
        owner = fb.pair_sessions_with_procs(sessions, procs)
        self.assertEqual(owner["a"]["pid"], 1)
        self.assertEqual(len(owner), 1)

    def test_no_procs_pairs_nothing(self):
        sessions = [self._s("a", "work", 10)]
        self.assertEqual(fb.pair_sessions_with_procs(sessions, []), {})


# ----------------------------------------------------------- model headroom

class TestModelHeadroom(ConfigGuard):
    def _acc(self):
        return acc("/h/.claude-account2", limits=[
            lim("Session", 20), lim("Weekly", 60),
            lim("Fable", 95, model_scoped=True)])

    def test_model_remaining_includes_matching_scoped_limit(self):
        # fable = min(session 80, weekly 40, fable 5) = 5
        self.assertEqual(fb._model_remaining(self._acc(), "fable"), 5)

    def test_model_remaining_ignores_other_models_scoped_limit(self):
        # opus has no scoped limit here → min(session 80, weekly 40) = 40
        self.assertEqual(fb._model_remaining(self._acc(), "opus"), 40)

    def test_model_remaining_none_when_not_ok(self):
        self.assertIsNone(fb._model_remaining(acc("/h/.claude", ok=False), "opus"))

    def test_model_candidates_respects_reserve_and_exclude(self):
        fb.config.DEMO = False
        fb.CFG["exclude_accounts"] = ["main"]
        fb.CFG["reserve_percent"] = {"account3": 20}
        fb._limits["data"] = {"available": True, "accounts": [
            acc("/h/.claude", headroom=90, limits=[lim("Weekly", 10)]),          # main: excluded
            acc("/h/.claude-account3", headroom=15, limits=[lim("Weekly", 85)]),  # 15% < 20 reserve → not ok
            acc("/h/.claude-account4", headroom=50, limits=[lim("Weekly", 50)]),  # ok
        ]}
        cands = {c["label"]: c for c in fb.model_candidates("opus")}
        self.assertNotIn("main", cands)                 # excluded
        self.assertFalse(cands["account3"]["ok"])       # below reserve
        self.assertTrue(cands["account4"]["ok"])
        # sorted by most remaining first
        self.assertEqual(fb.model_candidates("opus")[0]["label"], "account4")

    def test_model_candidates_only_account_ignores_exclude(self):
        fb.config.DEMO = False
        fb.CFG["exclude_accounts"] = ["main"]
        fb.CFG["reserve_percent"] = {}
        fb._limits["data"] = {"available": True, "accounts": [
            acc("/h/.claude", headroom=90, limits=[lim("Weekly", 10)])]}
        cands = fb.model_candidates("opus", only_account="main")
        self.assertEqual(len(cands), 1)                 # explicit choice honored
        self.assertTrue(cands[0]["ok"])


# ------------------------------------------------------------- limits summary

class TestLimitsByAccount(ConfigGuard):
    def test_reserve_blocked_and_available(self):
        fb.config.DEMO = False
        fb.CFG["reserve_percent"] = {"main": 20}
        fb._limits["data"] = {"available": True, "fetched_at": 1000, "accounts": [
            acc("/h/.claude", headroom=15, limits=[lim("Weekly", 85)]),           # 15 < 20 → blocked
            acc("/h/.claude-account2", headroom=50, limits=[lim("Weekly", 50)]),  # available
            acc("/h/.claude-account5", headroom=0,
                limits=[lim("Weekly", 100, exhausted=True, resets_in=3600)]),     # exhausted
        ]}
        out = fb.limits_by_account()
        self.assertTrue(out["main"]["reserve_blocked"])
        self.assertFalse(out["main"]["available"])
        self.assertTrue(out["account2"]["available"])
        self.assertTrue(out["account5"]["exhausted"])
        self.assertFalse(out["account5"]["available"])
        self.assertEqual(out["account5"]["worst"], "Weekly")

    def test_skips_not_ok_accounts(self):
        fb.config.DEMO = False
        fb.CFG["reserve_percent"] = {}
        fb._limits["data"] = {"available": True, "accounts": [acc("/h/.claude", ok=False)]}
        self.assertEqual(fb.limits_by_account(), {})

    def test_model_scoped_exhaustion_does_not_block_account(self):
        """A maxed model-scoped cap (Fable) must NOT mark the whole account
        exhausted while its all-model session/weekly still has headroom — the
        account stays available for an Opus/Sonnet mission. Regression: the
        model-blind exhausted flag wrote account8 (41% left, only Fable gone)
        off wholesale, so the router reported it exhausted."""
        fb.config.DEMO = False
        fb.CFG["reserve_percent"] = {}
        fb._limits["data"] = {"available": True, "fetched_at": 1000, "accounts": [
            acc("/h/.claude-account8", headroom=41, limits=[
                lim("Session", 0),
                lim("Weekly", 59),
                lim("Fable", 100, model_scoped=True, exhausted=True, resets_in=144748)]),
        ]}
        out = fb.limits_by_account()["account8"]
        self.assertFalse(out["exhausted"])       # Fable-only exhaustion ≠ account-wide
        self.assertTrue(out["available"])        # still pickable
        self.assertIsNone(out["worst"])          # no account-wide cap is the worst
        # the model-scoped block is still reported, for the session-status join
        self.assertEqual([s["label"] for s in out["scoped_exhausted"]], ["Fable"])
        self.assertEqual(out["scoped_exhausted"][0]["resets_at"], 1000 + 144748)

    def test_account_wide_exhaustion_still_blocks(self):
        """The umbrella Weekly (non-model-scoped) being gone DOES take the whole
        account out — every model shares that cap."""
        fb.config.DEMO = False
        fb.CFG["reserve_percent"] = {}
        fb._limits["data"] = {"available": True, "fetched_at": 1000, "accounts": [
            acc("/h/.claude-account5", headroom=0, limits=[
                lim("Weekly", 100, exhausted=True, resets_in=3600),
                lim("Fable", 84, model_scoped=True)]),
        ]}
        out = fb.limits_by_account()["account5"]
        self.assertTrue(out["exhausted"])
        self.assertFalse(out["available"])
        self.assertEqual(out["worst"], "Weekly")

    def test_router_availability_survives_fleetwide_fable_exhaustion(self):
        """The exact live fleet that produced 'every account is exhausted':
        Fable maxed across most accounts, umbrella Weekly gone on a few.
        Accounts that only lost Fable must stay available; only the
        umbrella-Weekly ones drop out — and an Opus mission routes to the
        most-headroom survivor rather than failing outright."""
        fb.config.DEMO = False
        fb.CFG["exclude_accounts"] = ["main"]
        fb.CFG["reserve_percent"] = {}

        def fable_gone(cd, hr, weekly_used):
            return acc(cd, headroom=hr, limits=[
                lim("Session", 0), lim("Weekly", weekly_used),
                lim("Fable", 100, model_scoped=True, exhausted=True, resets_in=1)])

        def weekly_gone(cd):
            return acc(cd, headroom=0, limits=[
                lim("Session", 0),
                lim("Weekly", 100, exhausted=True, resets_in=1),
                lim("Fable", 84, model_scoped=True)])

        fb._limits["data"] = {"available": True, "fetched_at": 1000, "accounts": [
            weekly_gone("/h/.claude"),                  # main — excluded + umbrella gone
            fable_gone("/h/.claude-account8", 41, 59),
            fable_gone("/h/.claude-account4", 15, 85),
            weekly_gone("/h/.claude-account5"),
        ]}
        lba = fb.limits_by_account()
        avail = sorted(a for a, d in lba.items()
                       if d["available"] and a not in fb.CFG["exclude_accounts"])
        self.assertEqual(avail, ["account4", "account8"])   # not "every account is exhausted"
        self.assertFalse(lba["account5"]["available"])      # umbrella weekly genuinely gone
        # an Opus mission routes to the most-headroom survivor
        best = fb.model_candidates("opus")[0]
        self.assertEqual(best["label"], "account8")
        self.assertTrue(best["ok"])


# ---------------------------------------------------------- reserve persist

class TestSetReserve(ConfigGuard):
    def setUp(self):
        super().setUp()
        self.tmp = tempfile.NamedTemporaryFile("w", suffix=".json", delete=False)
        json.dump({"pattern": "confid", "reserve_percent": {}}, self.tmp)
        self.tmp.close()
        fb.config.CONFIG_PATH = Path(self.tmp.name)
        fb.CFG["reserve_percent"] = {}
        fb._limits["data"] = None

    def tearDown(self):
        Path(self.tmp.name).unlink(missing_ok=True)
        super().tearDown()

    def test_set_persists_and_preserves_other_keys(self):
        res = fb.set_reserve("main", 20)
        self.assertTrue(res["ok"])
        self.assertEqual(fb.CFG["reserve_percent"], {"main": 20})
        disk = json.loads(Path(self.tmp.name).read_text())
        self.assertEqual(disk["reserve_percent"], {"main": 20})
        self.assertEqual(disk["pattern"], "confid")   # untouched

    def test_zero_removes_entry(self):
        fb.set_reserve("main", 20)
        fb.set_reserve("main", 0)
        self.assertNotIn("main", fb.CFG["reserve_percent"])

    def test_clamps_range(self):
        self.assertEqual(fb.set_reserve("main", 150)["percent"], 95)
        self.assertEqual(fb.set_reserve("main", -5)["percent"], 0)

    def test_rejects_non_numeric(self):
        self.assertFalse(fb.set_reserve("main", "lots")["ok"])


# ---------------------------------------------------------- dispatch log

class TestDispatchLog(ConfigGuard):
    def setUp(self):
        super().setUp()
        self.tmp = tempfile.NamedTemporaryFile("w", suffix=".jsonl", delete=False)
        for i in range(3):
            self.tmp.write(json.dumps({
                "ts": f"2026-07-19T0{i}:00:00", "session": f"mission-s{i}",
                "worktree": f"W{i}", "account": "account2",
                "mission_original": f"do thing {i}"}) + "\n")
        self.tmp.close()
        fb.DISPATCH_LOG = Path(self.tmp.name)
        self._run = fb.shell.run
        fb.shell.run = lambda *a, **k: (0, "mission-s2")   # only s2 is "live" in tmux

    def tearDown(self):
        fb.shell.run = self._run
        Path(self.tmp.name).unlink(missing_ok=True)
        super().tearDown()

    def test_newest_first_and_liveness(self):
        out = fb.read_dispatch_log()
        self.assertEqual(out["entries"][0]["session"], "mission-s2")   # newest first
        self.assertTrue(out["entries"][0]["alive"])                    # matches tmux
        self.assertFalse(out["entries"][1]["alive"])

    def test_limit(self):
        self.assertEqual(len(fb.read_dispatch_log(limit=2)["entries"]), 2)


# ------------------------------------------------------ deterministic dispatch

class TestDispatchContract(ConfigGuard):
    """Routing is deterministic and model + effort are the caller's job."""
    def setUp(self):
        super().setUp()
        fb.config.DEMO = True   # a refusal must come back before any thread launches

    def test_missing_model_or_effort_is_refused_cleanly(self):
        for kw in ({}, {"model": "opus"}, {"effort": "high"}):
            out = fb.start_dispatch("build the thing", **kw)
            self.assertFalse(out.get("ok", True))
            self.assertNotIn("job", out)
            self.assertIn("model", out["message"])

    def test_closeout_runs_without_model_or_effort(self):
        out = fb.start_dispatch("close out", worktree="w",
                                closeout_trunk="origin/main")
        self.assertIn("job", out)   # not refused — closeouts pick nothing


# ------------------------------------------------------------ finish tiers

class FakeGit:
    """Stand-in for fb.shell.run that answers the git calls start_finish makes."""
    def __init__(self, landed=True, porcelain="", branch="feat/x",
                 switch_rc=0, pull_rc=0):
        self.landed, self.porcelain, self.branch = landed, porcelain, branch
        self.switch_rc, self.pull_rc = switch_rc, pull_rc
        self.calls = []

    def __call__(self, cmd, cwd=None, timeout=None, **kw):
        self.calls.append(cmd)
        if "fetch" in cmd:
            return 0, ""
        if "merge-base" in cmd:
            return (0 if self.landed else 1), ""
        if "status" in cmd:
            return 0, self.porcelain
        if "rev-parse" in cmd:
            return 0, self.branch + "\n"
        if "switch" in cmd:
            return self.switch_rc, "" if self.switch_rc == 0 else "collision"
        if "pull" in cmd:
            return self.pull_rc, ""
        raise AssertionError(f"unexpected git call: {cmd}")

    def ran(self, word):
        return any(word in c for c in self.calls)


class TestStartFinish(ConfigGuard):
    """The finish button must scale its work to what's actually left: a
    landed branch never gets the full re-check treatment."""

    def setUp(self):
        super().setUp()
        fb.config.DEMO = False
        fb._closeouts.clear()
        self._saved = {n: getattr(fb, n) for n in ("run", "start_dispatch")}
        self._saved_git = {n: getattr(fb.gitrepo, n) for n in
                           ("discover_worktrees", "_base_ref")}
        self._saved_procs = fb.procs.claude_processes
        self._saved_scan = fb.transcripts.scan_sessions
        self._saved_send = fb.terminal.send_to_process
        fb.gitrepo.discover_worktrees = lambda: [
            {"name": "wt", "path": "/w/wt", "git": "/w/wt"}]
        fb.gitrepo._base_ref = lambda root: "origin/main"
        fb.procs.claude_processes = lambda: []
        self.sent = []
        fb.terminal.send_to_process = lambda pid, text: (
            self.sent.append(text) or {"ok": True})
        self.dispatched = []
        fb.start_dispatch = lambda brief, **kw: (
            self.dispatched.append((brief, kw)) or {"ok": True, "job": "j1"})

    def tearDown(self):
        for n, f in self._saved.items():
            setattr(fb, n, f)
        for n, f in self._saved_git.items():
            setattr(fb.gitrepo, n, f)
        fb.procs.claude_processes = self._saved_procs
        fb.transcripts.scan_sessions = self._saved_scan
        fb.terminal.send_to_process = self._saved_send
        super().tearDown()

    def live(self):
        # a realistic proc: real claude_processes() always carries "cmd", which
        # scan_sessions reads when start_finish classifies the live session
        fb.procs.claude_processes = lambda: [
            {"pid": 1, "cwd": "/w/wt", "tmux_target": "s:0",
             "cmd": "claude --dangerously-skip-permissions"}]

    def finish(self, **git):
        fb.shell.run = self.git = FakeGit(**git)
        return fb.start_finish("wt")

    # -- live terminal ------------------------------------------------------
    def test_live_landed_clean_sends_exit(self):
        self.live()
        out = self.finish(landed=True)
        self.assertEqual(out["mode"], "exit")
        self.assertEqual(self.sent, ["/exit"])

    def test_live_landed_dirty_gets_slim_brief(self):
        self.live()
        out = self.finish(landed=True, porcelain="?? scratch.txt\n")
        self.assertEqual(out["mode"], "slim")
        self.assertIn("already landed", self.sent[0])
        self.assertNotIn("merge origin/main into it", self.sent[0])

    def test_live_not_landed_gets_full_brief(self):
        self.live()
        out = self.finish(landed=False)
        self.assertEqual(out["mode"], "brief")
        self.assertIn("merge-base --is-ancestor", self.sent[0])

    # -- two-step: brief sent, then ✕ close ---------------------------------
    def test_brief_send_marks_the_card_for_step_two(self):
        self.live()
        out = self.finish(landed=False)
        self.assertEqual(out["mode"], "brief")
        self.assertIn("wt", fb._closeouts)
        self.assertIn("✕ close", out["message"])   # the toast teaches step two

    def test_close_while_unverified_reports_instead_of_rebriefing(self):
        # re-typing the brief would interrupt an agent mid-closeout; ✕ close
        # must only ever verify + /exit, or say why it can't
        self.live()
        self.finish(landed=False)
        out = self.finish(landed=False)
        self.assertEqual(out["mode"], "pending")
        self.assertFalse(out["ok"])
        self.assertIn("not landed", out["message"])
        self.assertEqual(len(self.sent), 1)        # the brief went exactly once

    def test_close_pending_names_the_leftover_dirt(self):
        self.live()
        self.finish(landed=False)
        out = self.finish(landed=True, porcelain=" M src/app.py\n?? tmp\n")
        self.assertEqual(out["mode"], "pending")
        self.assertIn("2 leftover file(s)", out["message"])

    def test_close_nudges_a_stalled_idle_agent(self):
        # the real deadlock: agent idle ('waiting'), one dirty file it won't
        # touch, no other session live — ✕ close types the specifics at it
        # instead of refusing forever
        import time as _t
        self.live()
        fb.transcripts.scan_sessions = lambda wts, procs, now: {
            "/w/wt": [{"sid": "s1", "pid": 1, "status": "waiting"}]}
        self.finish(landed=True, porcelain=" M keep.py\n")   # arms _closeouts
        fb._closeouts["wt"] = _t.time() - 120                 # briefed 2m ago
        before = fb._closeouts["wt"]
        out = self.finish(landed=True, porcelain=" M keep.py\n")
        self.assertEqual(out["mode"], "nudge")
        self.assertTrue(out["ok"])
        self.assertIn("keep.py", self.sent[-1])               # specifics typed
        self.assertIn("1 leftover file(s)", self.sent[-1])
        self.assertGreater(fb._closeouts["wt"], before)       # clock restarted

    def test_nudge_lists_porcelain_and_truncates_past_five(self):
        import time as _t
        self.live()
        fb.transcripts.scan_sessions = lambda wts, procs, now: {
            "/w/wt": [{"sid": "s1", "pid": 1, "status": "waiting"}]}
        porc = "".join(f"?? f{i}.tmp\n" for i in range(7))
        self.finish(landed=True, porcelain=porc)
        fb._closeouts["wt"] = _t.time() - 120
        out = self.finish(landed=True, porcelain=porc)
        self.assertEqual(out["mode"], "nudge")
        nudged = self.sent[-1]
        self.assertIn("?? f0.tmp", nudged)
        self.assertIn("?? f4.tmp", nudged)                    # 5th shown
        self.assertNotIn("?? f5.tmp", nudged)                 # 6th truncated
        self.assertIn("… and 2 more", nudged)

    def test_close_sends_you_to_chat_when_the_agent_is_stuck(self):
        # a nudge would collide with the open question dialog — refuse to chat
        import time as _t
        self.live()
        fb.transcripts.scan_sessions = lambda wts, procs, now: {
            "/w/wt": [{"sid": "s1", "pid": 1, "status": "needs_input"}]}
        self.finish(landed=False)
        fb._closeouts["wt"] = _t.time() - 120                 # past the guard
        out = self.finish(landed=False)
        self.assertEqual(out["mode"], "chat")
        self.assertFalse(out["ok"])
        self.assertIn("chat", out["message"])
        self.assertEqual(out["left"], "branch not landed on origin/main")
        self.assertEqual(len(self.sent), 1)                   # no nudge typed

    def test_working_session_refuses_close_even_past_the_guard(self):
        # the agent may be mid-closeout — refuse regardless of the clock
        import time as _t
        self.live()
        fb.transcripts.scan_sessions = lambda wts, procs, now: {
            "/w/wt": [{"sid": "s1", "pid": 1, "status": "working"}]}
        self.finish(landed=False)
        fb._closeouts["wt"] = _t.time() - 120
        out = self.finish(landed=False)
        self.assertEqual(out["mode"], "pending")
        self.assertEqual(len(self.sent), 1)                   # brief only

    def test_pending_refusal_carries_structured_fields(self):
        # under the 60s guard: refuse, but the frontend gets left/files/sent
        self.live()
        fb.transcripts.scan_sessions = lambda wts, procs, now: {
            "/w/wt": [{"sid": "s1", "pid": 1, "status": "waiting"}]}
        self.finish(landed=True, porcelain=" M a.py\n?? b\n")  # sent = now
        out = self.finish(landed=True, porcelain=" M a.py\n?? b\n")
        self.assertEqual(out["mode"], "pending")
        self.assertEqual(out["left"], "2 leftover file(s)")
        self.assertEqual(out["files"], [" M a.py", "?? b"])
        self.assertIn("sent", out)
        self.assertEqual(len(self.sent), 1)                   # no nudge yet

    def test_close_exits_once_the_landing_verifies(self):
        self.live()
        self.finish(landed=False)
        out = self.finish(landed=True)
        self.assertEqual(out["mode"], "exit")
        self.assertEqual(self.sent[-1], "/exit")
        self.assertNotIn("wt", fb._closeouts)      # step two done — flag gone

    def test_pending_close_dies_with_the_terminal(self):
        # agent exited on its own (or was killed): the two-step is moot and
        # finish drops to the normal no-terminal tiers, not a stale "pending"
        self.live()
        self.finish(landed=False)
        fb.procs.claude_processes = lambda: []
        out = self.finish(landed=False)
        self.assertEqual(out["mode"], "dispatch")
        self.assertNotIn("wt", fb._closeouts)

    # -- no terminal, landed ------------------------------------------------
    def test_landed_clean_on_feature_branch_parks_without_agent(self):
        out = self.finish(landed=True, branch="feat/x")
        self.assertEqual(out["mode"], "parked")
        self.assertTrue(self.git.ran("switch"))
        self.assertTrue(self.git.ran("pull"))
        self.assertEqual(self.dispatched, [])   # no agent, no account usage

    def test_landed_untracked_scratch_goes_to_the_slim_agent(self):
        # cleaning is a judgment call — an agent decides what's droppable
        out = self.finish(landed=True, porcelain="?? a.tmp\n?? b.tmp\n")
        self.assertEqual(out["mode"], "dispatch")
        self.assertIn("already landed", self.dispatched[0][0])
        self.assertFalse(self.git.ran("switch"))   # parking is the agent's job now

    def test_landed_clean_on_trunk_is_noop(self):
        out = self.finish(landed=True, branch="main")
        self.assertEqual(out["mode"], "noop")
        self.assertEqual(self.dispatched, [])

    def test_landed_tracked_dirt_dispatches_slim_closeout(self):
        # a real leftover diff might be meaningful — an agent must judge it,
        # but nothing already merged gets re-checked
        out = self.finish(landed=True, porcelain=" M src/app.py\n")
        self.assertEqual(out["mode"], "dispatch")
        brief, kw = self.dispatched[0]
        self.assertIn("already landed", brief)
        self.assertEqual(kw["model"], "haiku")

    def test_switch_failure_falls_back_to_agent(self):
        out = self.finish(landed=True, switch_rc=1)
        self.assertEqual(out["mode"], "dispatch")
        self.assertIn("already landed", self.dispatched[0][0])

    def test_pull_failure_still_parks_and_admits_it(self):
        out = self.finish(landed=True, pull_rc=1)
        self.assertEqual(out["mode"], "parked")
        self.assertIn("pull failed", out["message"])

    # -- no terminal, not landed -------------------------------------------
    def test_not_landed_dispatches_full_closeout(self):
        out = self.finish(landed=False)
        self.assertEqual(out["mode"], "dispatch")
        self.assertIn("merge-base --is-ancestor", self.dispatched[0][0])


class TestCloseoutBriefs(unittest.TestCase):
    def test_slim_brief_never_asks_for_a_merge(self):
        slim = fb.SLIM_CLOSEOUT_TEXT.format(trunk="origin/main")
        self.assertIn("already landed", slim)
        self.assertNotIn("merge origin/main into it", slim)
        self.assertNotIn("merge-base", slim)

    def test_both_briefs_park_on_the_trunk(self):
        for brief in (fb.CLOSEOUT_TEXT, fb.SLIM_CLOSEOUT_TEXT):
            self.assertIn("switch this worktree to the trunk branch",
                          brief.format(trunk="origin/main"))


# --------------------------------------------------------- one-shot closeout

class TestCloseoutShell(unittest.TestCase):
    def shell(self, model=None, brief="close out now", trunk="origin/main"):
        return fb.closeout_shell(Path("/homes/acct 2"), model, brief, trunk)

    def test_headless_then_verify_then_fallback(self):
        sh = self.shell()
        # order matters: headless run, git verification, interactive fallback
        self.assertLess(sh.index(" -p "), sh.index("merge-base --is-ancestor"))
        self.assertLess(sh.index("merge-base --is-ancestor"), sh.index("--continue"))
        self.assertIn("git merge-base --is-ancestor HEAD origin/main", sh)
        self.assertIn("exit 0", sh)                      # verified clean -> session dies
        self.assertIn("exec claude", sh)                 # failure -> interactive resume
        self.assertIn("--dangerously-skip-permissions", sh)

    def test_quotes_survive_shell(self):
        sh = self.shell(brief="don't break; rm -rf $(pwd)")
        self.assertIn(shlex.quote("don't break; rm -rf $(pwd)"), sh)
        self.assertIn(shlex.quote("/homes/acct 2"), sh)  # space in the home path

    def test_model_flag_only_when_given(self):
        self.assertIn("--model opus", self.shell(model="opus"))
        self.assertNotIn("--model", self.shell())

    def test_rescue_never_pins_the_model(self):
        # a haiku closeout must escalate on failure: the --continue resume
        # line carries no --model, so the account's default model takes over
        resume = [l for l in self.shell(model="haiku").splitlines()
                  if "--continue" in l]
        self.assertEqual(len(resume), 1)
        self.assertNotIn("--model", resume[0])


# --------------------------------------------------------- scheduled resumes

class ResumeGuard(ConfigGuard):
    """Isolate the auto-resume registry and its on-disk state file."""
    def setUp(self):
        super().setUp()
        fb.config.DEMO = False
        self.tmpdir = tempfile.mkdtemp(prefix="fb-resume-")
        self._state_path = fb.RESUME_STATE
        fb.RESUME_STATE = Path(self.tmpdir) / "resume.schedule.json"
        self._resumes = dict(fb._resumes)
        fb._resumes.clear()

    def tearDown(self):
        fb._resumes.clear()
        fb._resumes.update(self._resumes)
        fb.RESUME_STATE = self._state_path
        import shutil as _sh
        _sh.rmtree(self.tmpdir, ignore_errors=True)
        super().tearDown()


class TestScheduleResume(ResumeGuard):
    def test_due_is_reset_plus_default_delay(self):
        import time as _t
        reset = _t.time() + 1000
        out = fb.schedule_resume("wt", "s1", "account2", resets_at=reset)
        self.assertTrue(out["ok"])
        self.assertAlmostEqual(out["due_at"], reset + 60, delta=1)
        r = fb._resumes["wt|s1"]
        self.assertEqual(r["status"], "pending")
        self.assertTrue(fb.RESUME_STATE.exists())     # persisted at once

    def test_custom_delay_and_exact_time(self):
        import time as _t
        reset = _t.time() + 1000
        out = fb.schedule_resume("wt", "s1", "account2",
                                 resets_at=reset, delay_s=300)
        self.assertAlmostEqual(out["due_at"], reset + 300, delta=1)
        # an explicit due time wins over reset+delay
        at = _t.time() + 7200
        out = fb.schedule_resume("wt", "s1", "account2",
                                 resets_at=reset, due_at=at)
        self.assertAlmostEqual(out["due_at"], at, delta=1)

    def test_delay_clamped_to_a_day(self):
        import time as _t
        reset = _t.time() + 1000
        out = fb.schedule_resume("wt", "s1", "account2",
                                 resets_at=reset, delay_s=999999)
        self.assertAlmostEqual(out["due_at"], reset + 86400, delta=1)

    def test_past_reset_fires_on_next_pass(self):
        import time as _t
        out = fb.schedule_resume("wt", "s1", "account2",
                                 resets_at=_t.time() - 500)
        self.assertTrue(out["ok"])
        self.assertAlmostEqual(out["due_at"], _t.time() + 5, delta=2)

    def test_refuses_without_any_reset_time(self):
        fb._limits["data"] = None       # nothing known about the account
        out = fb.schedule_resume("wt", "s1", "account2")
        self.assertFalse(out["ok"])
        self.assertTrue(out.get("need_time"))

    def test_falls_back_to_server_side_reset_lookup(self):
        # client sent no resets_at, but the limits cache knows the account
        import time as _t
        now = _t.time()
        fb._limits["data"] = {"available": True, "fetched_at": now, "accounts": [
            acc("/h/.claude-account2", headroom=0,
                limits=[lim("Session", 100, exhausted=True, resets_in=3600)])]}
        out = fb.schedule_resume("wt", "s1", "account2")
        self.assertTrue(out["ok"])
        self.assertAlmostEqual(out["due_at"], now + 3600 + 60, delta=2)

    def test_demo_refuses(self):
        fb.config.DEMO = True
        self.assertFalse(fb.schedule_resume("wt", "s1", "a")["ok"])

    def test_cancel(self):
        import time as _t
        fb.schedule_resume("wt", "s1", "account2", resets_at=_t.time() + 100)
        self.assertTrue(fb.cancel_resume("wt", "s1")["ok"])
        self.assertNotIn("wt|s1", fb._resumes)
        self.assertFalse(fb.cancel_resume("wt", "s1")["ok"])   # nothing armed

    def test_persistence_roundtrip(self):
        import time as _t
        fb.schedule_resume("wt", "s1", "account2", resets_at=_t.time() + 100)
        saved = fb._resumes.pop("wt|s1")
        fb.load_resumes()
        self.assertEqual(fb._resumes["wt|s1"]["account"], saved["account"])
        self.assertEqual(fb._resumes["wt|s1"]["status"], "pending")


class TestLimitActiveUntil(ResumeGuard):
    """Fire-time verification: a schedule must not type at an agent whose
    account is still exhausted — and must not be fooled by a stale cache
    whose reset time already passed."""

    def setUp(self):
        super().setUp()
        self._cl = fb.limits.cached_limits
        fb.limits.cached_limits = lambda refresh=False: fb._limits["data"]

    def tearDown(self):
        fb.limits.cached_limits = self._cl
        super().tearDown()

    def _data(self, limits, fetched):
        fb._limits["data"] = {"available": True, "fetched_at": fetched,
                              "accounts": [acc("/h/.claude-account2",
                                               headroom=0, limits=limits)]}

    def test_account_wide_block_returns_future_reset(self):
        import time as _t
        now = _t.time()
        self._data([lim("Session", 100, exhausted=True, resets_in=3600)], now)
        self.assertAlmostEqual(
            fb._limit_active_until("account2", "opus-4-8", now),
            now + 3600, delta=1)

    def test_clear_account_returns_none(self):
        import time as _t
        now = _t.time()
        self._data([lim("Session", 20)], now)
        self.assertIsNone(fb._limit_active_until("account2", "opus-4-8", now))

    def test_stale_past_reset_is_treated_as_clear(self):
        # cclimits still says exhausted, but its reset time already passed —
        # a lagging upstream must not delay the resume forever
        import time as _t
        now = _t.time()
        self._data([lim("Session", 100, exhausted=True, resets_in=3600)],
                   now - 7200)
        self.assertIsNone(fb._limit_active_until("account2", "opus-4-8", now))

    def test_scoped_limit_blocks_only_its_own_model(self):
        import time as _t
        now = _t.time()
        self._data([lim("Session", 10),
                    lim("Fable", 100, model_scoped=True, exhausted=True,
                        resets_in=3600)], now)
        self.assertAlmostEqual(
            fb._limit_active_until("account2", "fable-5", now),
            now + 3600, delta=1)
        self.assertIsNone(fb._limit_active_until("account2", "opus-4-8", now))
        # model unknown -> count the scoped cap: a late resume beats a wasted one
        self.assertAlmostEqual(
            fb._limit_active_until("account2", None, now), now + 3600, delta=1)

    def test_unreadable_limits_verify_as_clear(self):
        fb._limits["data"] = {"available": False}
        self.assertIsNone(fb._limit_active_until("account2", "opus-4-8", 0))


class TestFireResume(ResumeGuard):
    """The armed moment's decision tree."""

    def setUp(self):
        super().setUp()
        self._saved = {n: getattr(fb, n) for n in
                       ("cached_state", "_tmux_resume")}
        self._saved_git = {"discover_worktrees": fb.gitrepo.discover_worktrees}
        self._saved_homes = fb.transcripts.claude_homes
        self._saved_lau = fb.limits._limit_active_until
        self._saved_send = fb.terminal.send_to_process
        fb.gitrepo.discover_worktrees = lambda: [
            {"name": "wt", "path": "/w/wt", "git": "/w/wt"}]
        fb.transcripts.claude_homes = lambda: [Path("/h/.claude-account2")]
        fb.limits._limit_active_until = lambda account, model, now: None
        self.sent, self.tmuxed = [], []
        fb.terminal.send_to_process = lambda pid, text: (
            self.sent.append((pid, text)) or {"ok": True, "message": "sent via tmux"})
        fb._tmux_resume = lambda wt, cwd, home, sid: (
            self.tmuxed.append((wt, cwd, str(home), sid))
            or {"ok": True, "message": "resumed in tmux"})

    def tearDown(self):
        for n, f in self._saved.items():
            setattr(fb, n, f)
        for n, f in self._saved_git.items():
            setattr(fb.gitrepo, n, f)
        fb.transcripts.claude_homes = self._saved_homes
        fb.limits._limit_active_until = self._saved_lau
        fb.terminal.send_to_process = self._saved_send
        super().tearDown()

    def board(self, status="limit", pid=None, reachable=True, handed=None,
              present=True, loose_pid=None):
        sess = {"sid": "s1", "status": status, "pid": pid, "cwd": "/w/wt/sub",
                "handed_to": handed}
        procs = [{"pid": pid, "reachable": reachable}] if pid else []
        if loose_pid:   # someone ELSE's live terminal in the same worktree
            procs.append({"pid": loose_pid, "reachable": True})
        fb.cached_state = lambda: {"worktrees": [
            {"name": "wt", "sessions": [sess] if present else [],
             "live_procs": procs}]}

    def arm(self):
        import time as _t
        fb.schedule_resume("wt", "s1", "account2", model="opus-4-8",
                           resets_at=_t.time() - 100)
        return "wt|s1"

    def test_already_resumed_session_is_left_alone(self):
        self.board(status="working", pid=9)
        fb.fire_resume(self.arm())
        self.assertEqual(fb._resumes["wt|s1"]["status"], "done")
        self.assertEqual(self.sent, [])
        self.assertEqual(self.tmuxed, [])

    def test_handed_off_session_is_left_alone(self):
        self.board(handed="account5")
        fb.fire_resume(self.arm())
        self.assertEqual(fb._resumes["wt|s1"]["status"], "done")
        self.assertIn("account5", fb._resumes["wt|s1"]["message"])
        self.assertEqual(self.sent, [])

    def test_still_limited_rearms_for_the_fresh_reset(self):
        import time as _t
        self.board()
        until = _t.time() + 5000
        fb.limits._limit_active_until = lambda account, model, now: until
        key = self.arm()
        fb.fire_resume(key)
        r = fb._resumes[key]
        self.assertEqual(r["status"], "pending")       # not failed — re-armed
        self.assertEqual(r["attempts"], 1)
        self.assertAlmostEqual(r["due_at"], until + 60, delta=1)
        self.assertEqual(self.sent, [])

    def test_rearm_gives_up_after_max_attempts(self):
        import time as _t
        self.board()
        fb.limits._limit_active_until = lambda account, model, now: _t.time() + 5000
        key = self.arm()
        fb._resumes[key]["attempts"] = fb.RESUME_MAX_ATTEMPTS - 1
        fb.fire_resume(key)
        self.assertEqual(fb._resumes[key]["status"], "failed")

    def test_clear_limit_types_into_the_sessions_own_terminal(self):
        self.board(pid=42)
        fb.fire_resume(self.arm())
        self.assertEqual(self.sent, [(42, "continue")])
        self.assertEqual(fb._resumes["wt|s1"]["status"], "done")
        self.assertEqual(self.tmuxed, [])

    def test_never_borrows_another_sessions_terminal(self):
        # unlike the manual button, the unattended path must not type
        # 'continue' at whatever other agent happens to live in the worktree
        self.board(pid=None, loose_pid=77)
        fb.fire_resume(self.arm())
        self.assertEqual(self.sent, [])
        self.assertEqual(len(self.tmuxed), 1)   # targeted at the sid instead

    def test_unreachable_terminal_falls_back_to_tmux_resume(self):
        # the Cursor case: a live process exists but can't be scripted
        self.board(pid=42, reachable=False)
        fb.fire_resume(self.arm())
        self.assertEqual(self.sent, [])
        self.assertEqual(self.tmuxed, [("wt", "/w/wt/sub", "/h/.claude-account2", "s1")])
        self.assertEqual(fb._resumes["wt|s1"]["status"], "done")

    def test_tmux_fallback_flags_the_stale_window(self):
        # the surviving Cursor window keeps showing the pre-resume state —
        # the schedule's outcome must say so, or the user reads it as a no-op
        self.board(pid=42, reachable=False)
        fb.fire_resume(self.arm())
        self.assertIn("stale view", fb._resumes["wt|s1"]["message"])

    def test_failed_send_falls_back_to_tmux_resume(self):
        fb.terminal.send_to_process = lambda pid, text: {"ok": False, "message": "no automation"}
        self.board(pid=42)
        fb.fire_resume(self.arm())
        self.assertEqual(len(self.tmuxed), 1)
        self.assertEqual(fb._resumes["wt|s1"]["status"], "done")

    def test_vanished_session_still_resumes_via_tmux(self):
        # aged out of the 48h window — the transcript is still resumable
        self.board(present=False)
        fb.fire_resume(self.arm())
        self.assertEqual(self.tmuxed[0][3], "s1")
        self.assertEqual(self.tmuxed[0][1], "/w/wt")   # falls back to the worktree path

    def test_tmux_failure_is_reported_not_swallowed(self):
        fb._tmux_resume = lambda *a: {"ok": False, "message": "tmux failed"}
        self.board()
        fb.fire_resume(self.arm())
        self.assertEqual(fb._resumes["wt|s1"]["status"], "failed")
        self.assertIn("tmux", fb._resumes["wt|s1"]["message"])

    def test_cancelled_schedule_never_fires(self):
        self.board(pid=42)
        key = self.arm()
        fb.cancel_resume("wt", "s1")
        fb.fire_resume(key)
        self.assertEqual(self.sent, [])


class TestDeliverText(unittest.TestCase):
    """Enter is pressed until the send is proven, then stops."""

    def setUp(self):
        self._run, self._sleep = fb.shell.run, fb.time.sleep
        fb.time.sleep = lambda s: None
        self.calls = []
        self.panes = ["❯ [Pasted text #1] still in the composer", "❯ \n"]

        def fake_run(cmd, **kw):
            self.calls.append(cmd)
            if "capture-pane" in cmd:
                return 0, self.panes.pop(0)
            return 0, ""
        fb.shell.run = fake_run

    def tearDown(self):
        fb.shell.run, fb.time.sleep = self._run, self._sleep

    def test_enters_until_sent(self):
        self.assertTrue(fb.deliver_text("sess", "continue"))
        enters = [c for c in self.calls if c[-1:] == ["Enter"]]
        self.assertEqual(len(enters), 2)      # unsent once, proven on the second
        pastes = [c for c in self.calls if "paste-buffer" in c]
        self.assertEqual(len(pastes), 1)      # pasted atomically, exactly once

    def test_gives_up_after_three_enters(self):
        self.panes = ["❯ stuck", "❯ stuck", "❯ stuck"]
        self.assertFalse(fb.deliver_text("sess", "continue"))
        enters = [c for c in self.calls if c[-1:] == ["Enter"]]
        self.assertEqual(len(enters), 3)


class TestComposerIdle(unittest.TestCase):
    """Readiness for the resume paste: a bare composer proves nothing while
    the reopened CLI is reloading or compacting — the observed failure was
    'continue' vanishing into the auto-compact while the bare prompt it left
    behind read as delivered."""

    def test_bare_composer_is_idle(self):
        self.assertTrue(fb.composer_idle(TestKickoffSent.IDLE_EMPTY))

    def test_running_turn_is_not_idle(self):
        self.assertFalse(fb.composer_idle(TestKickoffSent.MID_TURN))

    def test_compacting_is_not_idle(self):
        pane = ("✻ Compacting conversation… (esc to interrupt)\n"
                "────────────\n❯ \n────────────\n")
        self.assertFalse(fb.composer_idle(pane))

    def test_text_in_composer_is_not_idle(self):
        self.assertFalse(fb.composer_idle(TestKickoffSent.STUCK))

    def test_blank_pane_is_not_idle(self):
        self.assertFalse(fb.composer_idle(""))


class TestProvenInTranscript(unittest.TestCase):
    """The only accepted receipt for a resume send: the session file itself."""

    def setUp(self):
        self._sleep = fb.time.sleep
        fb.time.sleep = lambda s: None
        self.tmp = tempfile.mkdtemp(prefix="fb-proof-")
        self.fp = Path(self.tmp) / "s1.jsonl"
        self.fp.write_text(json.dumps(
            {"type": "user", "message": {"content": "continue"}}) + "\n")
        self.offset = self.fp.stat().st_size

    def tearDown(self):
        fb.time.sleep = self._sleep

    def append(self, entry):
        with open(self.fp, "a") as f:
            f.write(json.dumps(entry) + "\n")

    def test_message_past_offset_proves(self):
        self.append({"type": "user", "message": {"content": "continue"}})
        self.assertTrue(fb._proven_in_transcript(
            self.fp, self.offset, "continue", timeout_s=0.1))

    def test_pre_offset_message_does_not_prove(self):
        # the transcript held a 'continue' from before the send — only bytes
        # appended after it count
        self.assertFalse(fb._proven_in_transcript(
            self.fp, self.offset, "continue", timeout_s=0.1))

    def test_assistant_text_does_not_prove(self):
        self.append({"type": "assistant", "message":
                     {"content": [{"type": "text", "text": "continue"}]}})
        self.assertFalse(fb._proven_in_transcript(
            self.fp, self.offset, "continue", timeout_s=0.1))

    def test_list_content_counts(self):
        self.append({"type": "user", "message":
                     {"content": [{"type": "text", "text": "continue"}]}})
        self.assertTrue(fb._proven_in_transcript(
            self.fp, self.offset, "continue", timeout_s=0.1))

    def test_missing_file_is_unproven(self):
        self.assertFalse(fb._proven_in_transcript(
            Path(self.tmp) / "gone.jsonl", 0, "continue", timeout_s=0.1))


class TestTmuxResume(unittest.TestCase):
    """The fallback resume believes nothing but the transcript."""

    def setUp(self):
        self._saved = {n: getattr(fb, n) for n in
                       ("deliver_text", "_wait_composer_idle",
                        "_proven_in_transcript")}
        self._saved_run = fb.shell.run
        self._sleep = fb.time.sleep
        fb.time.sleep = lambda s: None
        self.home = Path(tempfile.mkdtemp(prefix="fb-tmuxres-"))
        proj = self.home / "projects" / "-w-wt"
        proj.mkdir(parents=True)
        (proj / "s1.jsonl").write_text("")
        self.waits, self.delivered = [], []
        fb.shell.run = lambda cmd, **kw: (0, "")
        fb._wait_composer_idle = lambda name, t: self.waits.append(t) or True
        fb.deliver_text = lambda name, text: self.delivered.append(text) or True
        fb._proven_in_transcript = lambda fp, off, text, timeout_s=20.0: True

    def tearDown(self):
        for n, f in self._saved.items():
            setattr(fb, n, f)
        fb.shell.run = self._saved_run
        fb.time.sleep = self._sleep

    def test_waits_out_reload_before_pasting(self):
        out = fb._tmux_resume("wt", "/w/wt", self.home, "s1")
        self.assertTrue(out["ok"])
        self.assertEqual(self.waits, [fb.RESUME_READY_S])  # settled, then pasted
        self.assertEqual(self.delivered, ["continue"])
        self.assertIn("attach", out["message"])

    def test_vanished_paste_retries_then_fails_honestly(self):
        fb._proven_in_transcript = lambda *a, **kw: False
        out = fb._tmux_resume("wt", "/w/wt", self.home, "s1")
        self.assertFalse(out["ok"])
        self.assertEqual(len(self.delivered), 3)           # three real attempts
        self.assertEqual(self.waits, [fb.RESUME_READY_S, 90.0, 90.0])
        self.assertIn("attach", out["message"])

    def test_missing_transcript_reports_unproven(self):
        home = Path(tempfile.mkdtemp(prefix="fb-nohome-"))
        (home / "projects").mkdir()
        out = fb._tmux_resume("wt", "/w/wt", home, "s1")
        self.assertTrue(out["ok"])
        self.assertIn("unproven", out["message"])

    def test_tmux_failure_reports(self):
        fb.shell.run = lambda cmd, **kw: (1, "boom")
        out = fb._tmux_resume("wt", "/w/wt", self.home, "s1")
        self.assertFalse(out["ok"])
        self.assertIn("tmux failed", out["message"])


# --------------------------------------------------------- demo integration

class TestDemoState(ConfigGuard):
    def setUp(self):
        super().setUp()
        fb.config.DEMO = True

    def test_demo_state_shape(self):
        st = fb.cached_state()
        self.assertIn("worktrees", st)
        self.assertIn("free_worktrees", st)
        self.assertTrue(all("availability" in w for w in st["worktrees"]))

    def test_demo_limits_and_topology(self):
        self.assertTrue(fb.cached_limits()["available"])
        self.assertTrue(fb.demo_topology()["groups"])


class TestHTTPSmoke(ConfigGuard):
    """Spin the real server in DEMO mode (no subprocess) and hit it."""
    def setUp(self):
        super().setUp()
        fb.config.DEMO = True
        self.srv = ThreadingHTTPServer(("127.0.0.1", 0), fb.Handler)
        self.port = self.srv.server_address[1]
        self.t = threading.Thread(target=self.srv.serve_forever, daemon=True)
        self.t.start()

    def tearDown(self):
        self.srv.shutdown()
        self.srv.server_close()
        super().tearDown()

    def _get(self, path):
        with urllib.request.urlopen(f"http://127.0.0.1:{self.port}{path}", timeout=5) as r:
            return r.status, r.read()

    def test_state_endpoint_json(self):
        status, body = self._get("/api/state")
        self.assertEqual(status, 200)
        self.assertIn("worktrees", json.loads(body))

    def test_index_served(self):
        status, body = self._get("/")
        self.assertEqual(status, 200)
        self.assertIn(b"orchestra", body)

    def test_query_string_route(self):
        status, _ = self._get("/?mission=hello")   # must not 404
        self.assertEqual(status, 200)

    def test_limits_and_topology_endpoints(self):
        self.assertEqual(self._get("/api/limits")[0], 200)
        self.assertEqual(self._get("/api/topology")[0], 200)

    def test_guide_served(self):
        status, body = self._get("/guide")
        self.assertEqual(status, 200)
        self.assertIn(b"closing out a mission", body)

    def test_state_carries_resume_schedules(self):
        _, body = self._get("/api/state")
        st = json.loads(body)
        self.assertIn("resumes", st)
        self.assertTrue(all("due_at" in r for r in st["resumes"].values()))

    def test_resume_schedule_refuses_in_demo(self):
        req = urllib.request.Request(
            f"http://127.0.0.1:{self.port}/api/resume/schedule",
            data=json.dumps({"worktree": "w", "sid": "s", "account": "a"}).encode(),
            headers={"Content-Type": "application/json"}, method="POST")
        with urllib.request.urlopen(req, timeout=5) as r:
            d = json.loads(r.read())
        self.assertFalse(d["ok"])
        self.assertIn("demo", d["message"])

    def test_finish_endpoint_refuses_in_demo(self):
        req = urllib.request.Request(
            f"http://127.0.0.1:{self.port}/api/finish",
            data=json.dumps({"worktree": "orbital-api"}).encode(),
            headers={"Content-Type": "application/json"}, method="POST")
        with urllib.request.urlopen(req, timeout=5) as r:
            d = json.loads(r.read())
        self.assertFalse(d["ok"])
        self.assertIn("demo", d["message"])

    def test_unknown_path_404(self):
        with self.assertRaises(urllib.error.HTTPError) as cm:
            self._get("/nope")
        self.assertEqual(cm.exception.code, 404)
        cm.exception.close()


if __name__ == "__main__":
    unittest.main(verbosity=2)
