#!/usr/bin/env python3
"""orchestr test suite — pure stdlib unittest, zero dependencies.

    python3 -m unittest discover -s tests        # from repo root
    python3 tests/test_orchestr.py             # or run directly

orchestr.py is a script (guarded by `if __name__ == "__main__"`), so importing
it here does NOT start the server. Data-driven functions read module globals
(CFG, _limits, DEMO); tests set those and restore them.
"""

import importlib.util
import json
import tempfile
import threading
import unittest
import urllib.request
from http.server import ThreadingHTTPServer
from pathlib import Path

# ---- load orchestr.py by path (it's a script, not a package) --------------
ROOT = Path(__file__).resolve().parent.parent
_spec = importlib.util.spec_from_file_location("orchestr", ROOT / "orchestr.py")
fb = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(fb)


def acc(config_dir, ok=True, headroom=None, limits=None):
    """Build a cclimits-shaped account dict."""
    return {"slug": Path(config_dir).name, "config_dir": config_dir, "ok": ok,
            "plan": "max", "headroom_percent": headroom, "limits": limits or []}


def lim(label, pct, model_scoped=False, exhausted=False, resets_in=None):
    return {"label": label, "group": "weekly" if label != "Session" else "session",
            "percent": pct, "remaining_percent": 100 - pct,
            "model_scoped": model_scoped, "exhausted_now": exhausted,
            "resets_in_seconds": resets_in}


class ConfigGuard(unittest.TestCase):
    """Snapshot & restore the module globals tests mutate."""
    def setUp(self):
        self._cfg = dict(fb.CFG)
        self._limits = dict(fb._limits)
        self._demo = fb.DEMO
        self._cpath = fb.CONFIG_PATH

    def tearDown(self):
        fb.CFG.clear(); fb.CFG.update(self._cfg)
        fb._limits.clear(); fb._limits.update(self._limits)
        fb.DEMO = self._demo
        fb.CONFIG_PATH = self._cpath


# ---------------------------------------------------------------- text utils

class TestText(ConfigGuard):
    def test_clean_strips_ansi(self):
        self.assertEqual(fb._clean("\x1b[1mHi\x1b[22m there"), "Hi there")

    def test_clean_collapses_whitespace_and_tags(self):
        self.assertEqual(fb._clean("a\n\n  b   <x>c</x>"), "a b c")

    def test_clean_truncates_with_ellipsis(self):
        out = fb._clean("a" * 300, 240)
        self.assertEqual(len(out), 240)
        self.assertTrue(out.endswith("…"))

    def test_real_prompt_rejects_slash_command(self):
        self.assertIsNone(fb._real_prompt("/model opus"))

    def test_real_prompt_rejects_caveat_and_machine_text(self):
        self.assertIsNone(fb._real_prompt("Caveat: generated by a local command"))
        self.assertIsNone(fb._real_prompt("<command-message>effort</command-message>"))
        self.assertIsNone(fb._real_prompt("<system-reminder>hi</system-reminder>"))
        self.assertIsNone(fb._real_prompt("here is toolu_01ABCdef noise"))
        self.assertIsNone(fb._real_prompt("<local-command-stdout>x</local-command-stdout>"))

    def test_real_prompt_accepts_real_text(self):
        self.assertEqual(fb._real_prompt("Build a dark-mode toggle"),
                         "Build a dark-mode toggle")

    def test_osa_escape(self):
        self.assertEqual(fb._osa_escape('a"b\\c'), 'a\\"b\\\\c')


# ------------------------------------------------------------ account / paths

class TestAccounts(ConfigGuard):
    def test_account_label(self):
        self.assertEqual(fb.account_label(Path.home() / ".claude"), "main")
        self.assertEqual(fb.account_label(Path.home() / ".claude-account8"), "account8")
        self.assertEqual(fb.account_label(Path.home() / ".claude-work"), "work")

    def test_munge(self):
        self.assertEqual(fb.munge("/Users/a/Downloads/ConfidAI"),
                         "-Users-a-Downloads-ConfidAI")

    def test_account_reserve_lookup_and_default(self):
        fb.CFG["reserve_percent"] = {"main": 20, "*": 5}
        self.assertEqual(fb.account_reserve("main"), 20)
        self.assertEqual(fb.account_reserve("account2"), 5)   # falls back to "*"
        fb.CFG["reserve_percent"] = {}
        self.assertEqual(fb.account_reserve("main"), 0)


# ---------------------------------------------------------- worktree matching

class TestMatchWorktree(unittest.TestCase):
    def test_longest_prefix_wins(self):
        prefixes = {"/d/ConfidAI": fb.munge("/d/ConfidAI"),
                    "/d/ConfidAI-security-audit": fb.munge("/d/ConfidAI-security-audit")}
        # a project under the audit worktree must not be swallowed by ConfidAI
        proj = fb.munge("/d/ConfidAI-security-audit") + "-backend"
        self.assertEqual(fb.match_worktree(proj, prefixes), "/d/ConfidAI-security-audit")

    def test_exact_and_subdir_match(self):
        prefixes = {"/d/app": fb.munge("/d/app")}
        self.assertEqual(fb.match_worktree(fb.munge("/d/app"), prefixes), "/d/app")
        self.assertEqual(fb.match_worktree(fb.munge("/d/app") + "-sub", prefixes), "/d/app")

    def test_no_match(self):
        prefixes = {"/d/app": fb.munge("/d/app")}
        self.assertIsNone(fb.match_worktree(fb.munge("/d/other"), prefixes))


# --------------------------------------------------------- session status

class TestClassifySession(unittest.TestCase):
    W = 90  # working_s

    def test_recent_is_working_regardless_of_liveness(self):
        self.assertEqual(fb.classify_session(5, False, [], 0, False, self.W)[0], "working")

    def test_needs_input_on_pending_question(self):
        st, _ = fb.classify_session(200, True, ["AskUserQuestion"], 0, False, self.W)
        self.assertEqual(st, "needs_input")

    def test_pending_workflow_keeps_working(self):
        st, _ = fb.classify_session(3600, True, [], 1, False, self.W)
        self.assertEqual(st, "working")

    def test_skip_perms_tool_run_is_working_not_blocked(self):
        st, tool = fb.classify_session(200, True, ["Bash"], 0, True, self.W)
        self.assertEqual(st, "working")
        self.assertTrue(tool)

    def test_pending_tool_without_skip_perms_is_blocked(self):
        st, _ = fb.classify_session(200, True, ["Bash"], 0, False, self.W)
        self.assertEqual(st, "blocked")

    def test_idle_alive_is_waiting(self):
        self.assertEqual(fb.classify_session(200, True, [], 0, False, self.W)[0], "waiting")

    def test_not_alive_is_ended(self):
        self.assertEqual(fb.classify_session(200, False, [], 0, False, self.W)[0], "ended")


# ------------------------------------------------ session <-> terminal pairing

class TestPairSessionsWithProcs(unittest.TestCase):
    """Which terminal belongs to which chat, for a worktree running several."""

    def _s(self, sid, account, age):
        return {"sid": sid, "account": account, "age_s": age}

    def _p(self, pid, account):
        return {"pid": pid, "account": account}

    def test_pairs_by_account(self):
        sessions = [self._s("a", "work", 10), self._s("b", "personal", 20)]
        procs = [self._p(1, "personal"), self._p(2, "work")]
        owner = fb.pair_sessions_with_procs(sessions, procs)
        self.assertEqual(owner["a"]["pid"], 2)
        self.assertEqual(owner["b"]["pid"], 1)

    def test_account_match_beats_freshness(self):
        # the fresher session has no process on its account; it must not take
        # the one that demonstrably belongs to the older session
        sessions = [self._s("fresh", "spare", 5), self._s("old", "work", 900)]
        procs = [self._p(7, "work")]
        owner = fb.pair_sessions_with_procs(sessions, procs)
        self.assertNotIn("fresh", owner)
        self.assertEqual(owner["old"]["pid"], 7)

    def test_falls_back_to_freshness_when_account_unknown(self):
        # environment unreadable -> accounts are None -> old slot behaviour
        sessions = [self._s("a", "work", 10), self._s("b", "work", 20)]
        procs = [self._p(1, None)]
        owner = fb.pair_sessions_with_procs(sessions, procs)
        self.assertEqual(owner["a"]["pid"], 1)
        self.assertNotIn("b", owner)

    def test_never_assigns_one_process_twice(self):
        sessions = [self._s("a", "work", 10), self._s("b", "work", 20)]
        procs = [self._p(1, "work")]
        owner = fb.pair_sessions_with_procs(sessions, procs)
        self.assertEqual(len(owner), 1)
        self.assertEqual({o["pid"] for o in owner.values()}, {1})

    def test_more_procs_than_sessions_leaves_leftovers(self):
        sessions = [self._s("a", "work", 10)]
        procs = [self._p(1, "work"), self._p(2, "spare")]
        owner = fb.pair_sessions_with_procs(sessions, procs)
        self.assertEqual(owner["a"]["pid"], 1)
        self.assertEqual(len(owner), 1)

    def test_no_procs_pairs_nothing(self):
        sessions = [self._s("a", "work", 10)]
        self.assertEqual(fb.pair_sessions_with_procs(sessions, []), {})


# ----------------------------------------------------------- model headroom

class TestModelHeadroom(ConfigGuard):
    def _acc(self):
        return acc("/h/.claude-account2", limits=[
            lim("Session", 20), lim("Weekly", 60),
            lim("Fable", 95, model_scoped=True)])

    def test_model_remaining_includes_matching_scoped_limit(self):
        # fable = min(session 80, weekly 40, fable 5) = 5
        self.assertEqual(fb._model_remaining(self._acc(), "fable"), 5)

    def test_model_remaining_ignores_other_models_scoped_limit(self):
        # opus has no scoped limit here → min(session 80, weekly 40) = 40
        self.assertEqual(fb._model_remaining(self._acc(), "opus"), 40)

    def test_model_remaining_none_when_not_ok(self):
        self.assertIsNone(fb._model_remaining(acc("/h/.claude", ok=False), "opus"))

    def test_model_candidates_respects_reserve_and_exclude(self):
        fb.DEMO = False
        fb.CFG["exclude_accounts"] = ["main"]
        fb.CFG["reserve_percent"] = {"account3": 20}
        fb._limits["data"] = {"available": True, "accounts": [
            acc("/h/.claude", headroom=90, limits=[lim("Weekly", 10)]),          # main: excluded
            acc("/h/.claude-account3", headroom=15, limits=[lim("Weekly", 85)]),  # 15% < 20 reserve → not ok
            acc("/h/.claude-account4", headroom=50, limits=[lim("Weekly", 50)]),  # ok
        ]}
        cands = {c["label"]: c for c in fb.model_candidates("opus")}
        self.assertNotIn("main", cands)                 # excluded
        self.assertFalse(cands["account3"]["ok"])       # below reserve
        self.assertTrue(cands["account4"]["ok"])
        # sorted by most remaining first
        self.assertEqual(fb.model_candidates("opus")[0]["label"], "account4")

    def test_model_candidates_only_account_ignores_exclude(self):
        fb.DEMO = False
        fb.CFG["exclude_accounts"] = ["main"]
        fb.CFG["reserve_percent"] = {}
        fb._limits["data"] = {"available": True, "accounts": [
            acc("/h/.claude", headroom=90, limits=[lim("Weekly", 10)])]}
        cands = fb.model_candidates("opus", only_account="main")
        self.assertEqual(len(cands), 1)                 # explicit choice honored
        self.assertTrue(cands[0]["ok"])


# ------------------------------------------------------------- limits summary

class TestLimitsByAccount(ConfigGuard):
    def test_reserve_blocked_and_available(self):
        fb.DEMO = False
        fb.CFG["reserve_percent"] = {"main": 20}
        fb._limits["data"] = {"available": True, "fetched_at": 1000, "accounts": [
            acc("/h/.claude", headroom=15, limits=[lim("Weekly", 85)]),           # 15 < 20 → blocked
            acc("/h/.claude-account2", headroom=50, limits=[lim("Weekly", 50)]),  # available
            acc("/h/.claude-account5", headroom=0,
                limits=[lim("Weekly", 100, exhausted=True, resets_in=3600)]),     # exhausted
        ]}
        out = fb.limits_by_account()
        self.assertTrue(out["main"]["reserve_blocked"])
        self.assertFalse(out["main"]["available"])
        self.assertTrue(out["account2"]["available"])
        self.assertTrue(out["account5"]["exhausted"])
        self.assertFalse(out["account5"]["available"])
        self.assertEqual(out["account5"]["worst"], "Weekly")

    def test_skips_not_ok_accounts(self):
        fb.DEMO = False
        fb.CFG["reserve_percent"] = {}
        fb._limits["data"] = {"available": True, "accounts": [acc("/h/.claude", ok=False)]}
        self.assertEqual(fb.limits_by_account(), {})

    def test_model_scoped_exhaustion_does_not_block_account(self):
        """A maxed model-scoped cap (Fable) must NOT mark the whole account
        exhausted while its all-model session/weekly still has headroom — the
        account stays available for an Opus/Sonnet mission. Regression: the
        model-blind exhausted flag wrote account8 (41% left, only Fable gone)
        off wholesale, so the router reported it exhausted."""
        fb.DEMO = False
        fb.CFG["reserve_percent"] = {}
        fb._limits["data"] = {"available": True, "fetched_at": 1000, "accounts": [
            acc("/h/.claude-account8", headroom=41, limits=[
                lim("Session", 0),
                lim("Weekly", 59),
                lim("Fable", 100, model_scoped=True, exhausted=True, resets_in=144748)]),
        ]}
        out = fb.limits_by_account()["account8"]
        self.assertFalse(out["exhausted"])       # Fable-only exhaustion ≠ account-wide
        self.assertTrue(out["available"])        # still pickable
        self.assertIsNone(out["worst"])          # no account-wide cap is the worst
        # the model-scoped block is still reported, for the session-status join
        self.assertEqual([s["label"] for s in out["scoped_exhausted"]], ["Fable"])
        self.assertEqual(out["scoped_exhausted"][0]["resets_at"], 1000 + 144748)

    def test_account_wide_exhaustion_still_blocks(self):
        """The umbrella Weekly (non-model-scoped) being gone DOES take the whole
        account out — every model shares that cap."""
        fb.DEMO = False
        fb.CFG["reserve_percent"] = {}
        fb._limits["data"] = {"available": True, "fetched_at": 1000, "accounts": [
            acc("/h/.claude-account5", headroom=0, limits=[
                lim("Weekly", 100, exhausted=True, resets_in=3600),
                lim("Fable", 84, model_scoped=True)]),
        ]}
        out = fb.limits_by_account()["account5"]
        self.assertTrue(out["exhausted"])
        self.assertFalse(out["available"])
        self.assertEqual(out["worst"], "Weekly")

    def test_router_availability_survives_fleetwide_fable_exhaustion(self):
        """The exact live fleet that produced 'every account is exhausted':
        Fable maxed across most accounts, umbrella Weekly gone on a few.
        Accounts that only lost Fable must stay available; only the
        umbrella-Weekly ones drop out — and an Opus mission routes to the
        most-headroom survivor rather than failing outright."""
        fb.DEMO = False
        fb.CFG["exclude_accounts"] = ["main"]
        fb.CFG["reserve_percent"] = {}

        def fable_gone(cd, hr, weekly_used):
            return acc(cd, headroom=hr, limits=[
                lim("Session", 0), lim("Weekly", weekly_used),
                lim("Fable", 100, model_scoped=True, exhausted=True, resets_in=1)])

        def weekly_gone(cd):
            return acc(cd, headroom=0, limits=[
                lim("Session", 0),
                lim("Weekly", 100, exhausted=True, resets_in=1),
                lim("Fable", 84, model_scoped=True)])

        fb._limits["data"] = {"available": True, "fetched_at": 1000, "accounts": [
            weekly_gone("/h/.claude"),                  # main — excluded + umbrella gone
            fable_gone("/h/.claude-account8", 41, 59),
            fable_gone("/h/.claude-account4", 15, 85),
            weekly_gone("/h/.claude-account5"),
        ]}
        lba = fb.limits_by_account()
        avail = sorted(a for a, d in lba.items()
                       if d["available"] and a not in fb.CFG["exclude_accounts"])
        self.assertEqual(avail, ["account4", "account8"])   # not "every account is exhausted"
        self.assertFalse(lba["account5"]["available"])      # umbrella weekly genuinely gone
        # an Opus mission routes to the most-headroom survivor
        best = fb.model_candidates("opus")[0]
        self.assertEqual(best["label"], "account8")
        self.assertTrue(best["ok"])


# ---------------------------------------------------------- reserve persist

class TestSetReserve(ConfigGuard):
    def setUp(self):
        super().setUp()
        self.tmp = tempfile.NamedTemporaryFile("w", suffix=".json", delete=False)
        json.dump({"pattern": "confid", "reserve_percent": {}}, self.tmp)
        self.tmp.close()
        fb.CONFIG_PATH = Path(self.tmp.name)
        fb.CFG["reserve_percent"] = {}
        fb._limits["data"] = None

    def tearDown(self):
        Path(self.tmp.name).unlink(missing_ok=True)
        super().tearDown()

    def test_set_persists_and_preserves_other_keys(self):
        res = fb.set_reserve("main", 20)
        self.assertTrue(res["ok"])
        self.assertEqual(fb.CFG["reserve_percent"], {"main": 20})
        disk = json.loads(Path(self.tmp.name).read_text())
        self.assertEqual(disk["reserve_percent"], {"main": 20})
        self.assertEqual(disk["pattern"], "confid")   # untouched

    def test_zero_removes_entry(self):
        fb.set_reserve("main", 20)
        fb.set_reserve("main", 0)
        self.assertNotIn("main", fb.CFG["reserve_percent"])

    def test_clamps_range(self):
        self.assertEqual(fb.set_reserve("main", 150)["percent"], 95)
        self.assertEqual(fb.set_reserve("main", -5)["percent"], 0)

    def test_rejects_non_numeric(self):
        self.assertFalse(fb.set_reserve("main", "lots")["ok"])


# ---------------------------------------------------------- dispatch log

class TestDispatchLog(ConfigGuard):
    def setUp(self):
        super().setUp()
        self.tmp = tempfile.NamedTemporaryFile("w", suffix=".jsonl", delete=False)
        for i in range(3):
            self.tmp.write(json.dumps({
                "ts": f"2026-07-19T0{i}:00:00", "session": f"mission-s{i}",
                "worktree": f"W{i}", "account": "account2",
                "mission_original": f"do thing {i}"}) + "\n")
        self.tmp.close()
        fb.DISPATCH_LOG = Path(self.tmp.name)
        self._run = fb.run
        fb.run = lambda *a, **k: (0, "mission-s2")   # only s2 is "live" in tmux

    def tearDown(self):
        fb.run = self._run
        Path(self.tmp.name).unlink(missing_ok=True)
        super().tearDown()

    def test_newest_first_and_liveness(self):
        out = fb.read_dispatch_log()
        self.assertEqual(out["entries"][0]["session"], "mission-s2")   # newest first
        self.assertTrue(out["entries"][0]["alive"])                    # matches tmux
        self.assertFalse(out["entries"][1]["alive"])

    def test_limit(self):
        self.assertEqual(len(fb.read_dispatch_log(limit=2)["entries"]), 2)


# --------------------------------------------------------- demo integration

class TestDemoState(ConfigGuard):
    def setUp(self):
        super().setUp()
        fb.DEMO = True

    def test_demo_state_shape(self):
        st = fb.cached_state()
        self.assertIn("worktrees", st)
        self.assertIn("free_worktrees", st)
        self.assertTrue(all("availability" in w for w in st["worktrees"]))

    def test_demo_limits_and_topology(self):
        self.assertTrue(fb.cached_limits()["available"])
        self.assertTrue(fb.demo_topology()["groups"])


class TestHTTPSmoke(ConfigGuard):
    """Spin the real server in DEMO mode (no subprocess) and hit it."""
    def setUp(self):
        super().setUp()
        fb.DEMO = True
        self.srv = ThreadingHTTPServer(("127.0.0.1", 0), fb.Handler)
        self.port = self.srv.server_address[1]
        self.t = threading.Thread(target=self.srv.serve_forever, daemon=True)
        self.t.start()

    def tearDown(self):
        self.srv.shutdown()
        self.srv.server_close()
        super().tearDown()

    def _get(self, path):
        with urllib.request.urlopen(f"http://127.0.0.1:{self.port}{path}", timeout=5) as r:
            return r.status, r.read()

    def test_state_endpoint_json(self):
        status, body = self._get("/api/state")
        self.assertEqual(status, 200)
        self.assertIn("worktrees", json.loads(body))

    def test_index_served(self):
        status, body = self._get("/")
        self.assertEqual(status, 200)
        self.assertIn(b"orchestr", body)

    def test_query_string_route(self):
        status, _ = self._get("/?mission=hello")   # must not 404
        self.assertEqual(status, 200)

    def test_limits_and_topology_endpoints(self):
        self.assertEqual(self._get("/api/limits")[0], 200)
        self.assertEqual(self._get("/api/topology")[0], 200)

    def test_guide_served(self):
        status, body = self._get("/guide")
        self.assertEqual(status, 200)
        self.assertIn(b"closing out a mission", body)

    def test_finish_endpoint_refuses_in_demo(self):
        req = urllib.request.Request(
            f"http://127.0.0.1:{self.port}/api/finish",
            data=json.dumps({"worktree": "orbital-api"}).encode(),
            headers={"Content-Type": "application/json"}, method="POST")
        with urllib.request.urlopen(req, timeout=5) as r:
            d = json.loads(r.read())
        self.assertFalse(d["ok"])
        self.assertIn("demo", d["message"])

    def test_unknown_path_404(self):
        with self.assertRaises(urllib.error.HTTPError) as cm:
            self._get("/nope")
        self.assertEqual(cm.exception.code, 404)
        cm.exception.close()


if __name__ == "__main__":
    unittest.main(verbosity=2)
